# Generated by Django 5.2.8 on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coloranalysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coloranalysisresult",
            name="try_on_images",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coloranalysisresult",
            name="try_on_error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
